### PR TITLE
Preserve end of line if any

### PR DESCRIPTION
**Pull request by PierrickP**
Detect and add same end of line if any

### how to test

Notice the **%** at the end (mean no eof)

image

### CODE REVIEW

**Comment by PierrickP** [comment]
image

**Comment by kesla** [comment]
wow. Very cool. Like it. Thanks.

**Comment by kesla** [comment]
@PierrickP would you consider this to be a breaking change or not? I'm uncertain tbh so would like your pov

**Comment by PierrickP** [comment]
Good question.
**Yes** is the most safe, because this PR modify previous behavior.
Even if for me the previous behavior was a *bug* :)

**Comment by PierrickP** [comment]
any news ?

**Comment by kesla** [comment]
@PierrickP hey sorry, been a bit busy. Merged & released in the newest version of `sort-json`! Thanks for the addition!

**Pull request merged**
